name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable
      run: pyinstaller src/main.py --onefile --noconfirm --name hon-log --icon=assets/img/favicon.ico --add-data "assets/img;assets/img" --noconsole

    - name: Get version from tag
      id: version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/hon-log.exe
        body: |
          貸出履歴は [こちら](https://www.lib.kyutech.ac.jp/opac/user/top) からダウンロードできます。
          九工大IDでのログインが必要です。

          ## ダウンロード
          - ### [Windows](https://github.com/pantsman-jp/hon-log/releases/download/${{ steps.version.outputs.VERSION }}/hon-log.exe)

          ---
          Copyright (c) 2026 @pantsman-jp
        token: ${{ secrets.GITHUB_TOKEN }}